### ISSUE TITLE
Analytical Workflows Project Proposal

### ISSUE THREAD

**Issue by zechmeunier** [zechmeunier/CRAZIE#1]

**Comment by howardre** [comment]
I thought you did a great job of intermixing visuals with text for your presentation, and I really liked how you laid out your research questions and their associated methods to lead into your workflow diagram.

**Comment by Juniper41** [comment]
It looks like you have your research plan very well thought out and organized. Good luck utilizing your bayesian model. Our lab (Terry Lab) utilizes a lot of Bayesian models, reach out if you want some help or talking through stuff.

**Comment by breshears-logan** [comment]
You did a great job of explaining the technical terms, and I liked how you used a conceptual model to highlight your anticipated workflow.

**Comment by McLeodMJ** [comment]
Hi Zech!
You have very clear research objectives and an impressive workflow. I would suggest FW 544- Quantitative Decision Analysis with Jim Peterson, if you haven't already taken it. It was a great class for me to learn and practice Bayesian models in R.

**Comment by Coffee-Powered-Scientist** [comment]
Good incorporation of a workflow diagram.
