### ISSUE TITLE
Analytical Workflows Project Report

### ISSUE THREAD

**Issue by zechmeunier** [zechmeunier/CRAZIE#2]

**Comment by Juniper41** [comment]
Great job! Looks like your leap into R is going pretty smoothly. It's unfortunate to have parts of a project that you have to shelve for another time, but it's super important to realize what is attainable/accomplishable and when it's too much or not feasible.

**Comment by howardre** [comment]
It was nice to see visually which portions of your workflow had to be eliminated and I thought it was nice to see how you're going to attain your revised goals week by week

**Comment by Angelika-Kurthen** [comment]
I appreciate the fact that you are open about not being able to meet all your goals for the term. This happens to me all the time and it is refreshing to see that I'm not the only one.

**Comment by jwongala** [comment]
Great to hear that you've moved a lot of analyses from excel to R and I like how you outlined your goals.

**Comment by Coffee-Powered-Scientist** [comment]
Nice presentation, don't worry about having to forgo parts of your project for the sake of time/organization. You want to do things well, not just quickly!

**Comment by McLeodMJ** [comment]
Great work! Data entry is tedious but important. I liked your weekly goals and found them to be reasonable. I think I am going to make my own weekly goals after class, thanks for the inspiration!

**Comment by jessealaney** [comment]
Your workflow looks complex but well developed and understandable. It seems like you have a good grasp on what parts of your project you will realistically be able to get done this term! Well done!
