### ISSUE TITLE
Analytical Workflows Project Summary

### ISSUE THREAD

**Issue by zechmeunier** [zechmeunier/CRAZIE#5]

**Comment by McLeodMJ** [comment]
Hi Zech! Congrats on your major progress! I know you had a lot of data entry to do so congrats on making all the progress that you did. General statement, I have found that using the different apply() functions is also a helpful alternative to for loops. I look forward to seeing your work and you can expect some MCMC- Rstan questions from me in the near future!

**Comment by zechmeunier** [comment]
Thanks! I appreciate your comments, and I'm definitely interested in seeing what you find too. I'll be sure to reach out once I get to the Bayesian stats stage.
